from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from core.types import AnalysisPlan, IntentResult, SQLCandidate, TableSchema
from llm.client import LLMClient, LLMClientError
from llm.prompts import build_sql_generation_prompt
from memory.session_memory import SessionMemory
from sql_layer.utils import quote_identifier


@dataclass
class SQLGenerator:
    llm_client: LLMClient | None = None
    max_result_rows: int = 100

    def generate(
        self,
        question: str,
        schema: TableSchema,
        intent: IntentResult,
        memory: SessionMemory | None = None,
        analysis_plan: AnalysisPlan | None = None,
    ) -> SQLCandidate:
        if analysis_plan is not None:
            plan_candidate = self.generate_from_plan(question, schema, intent, analysis_plan)
            if plan_candidate is not None:
                return plan_candidate
        llm_candidate = self._try_llm(question, schema, intent, analysis_plan)
        if llm_candidate is not None:
            return llm_candidate
        return self._generate_with_rules(question, schema, intent, memory)

    def generate_from_plan(
        self,
        question: str,
        schema: TableSchema,
        intent: IntentResult,
        plan: AnalysisPlan,
    ) -> SQLCandidate | None:
        candidate = self._generate_with_rules(question, schema, intent, None)
        if candidate.cannot_answer:
            return candidate
        candidate.generated_from_plan = True
        candidate.confidence = 0.85
        candidate.notes.append(f"Generated from analysis plan: {plan.goal}")
        return candidate

    def _try_llm(
        self,
        question: str,
        schema: TableSchema,
        intent: IntentResult,
        analysis_plan: AnalysisPlan | None = None,
    ) -> SQLCandidate | None:
        if self.llm_client is None or not self.llm_client.is_available:
            return None
        try:
            prompt = build_sql_generation_prompt(question, schema, intent)
            payload = self.llm_client.generate_json(prompt)
        except LLMClientError:
            return None

        if payload.get("cannot_answer"):
            return SQLCandidate(
                sql="",
                used_tables=[],
                used_columns=[],
                reasoning=str(payload.get("reasoning", "")),
                cannot_answer=True,
                error_message=str(payload.get("reasoning", "Question cannot be answered.")),
            )

        sql = str(payload.get("sql", "")).strip()
        if not sql:
            return None
        return SQLCandidate(
            sql=sql,
            used_tables=[str(t) for t in payload.get("used_tables", [schema.table_name])],
            used_columns=[str(c) for c in payload.get("used_columns", [])],
            reasoning=str(payload.get("reasoning", "Generated by LLM.")),
        )

    def _generate_with_rules(
        self,
        question: str,
        schema: TableSchema,
        intent: IntentResult,
        memory: SessionMemory | None = None,
    ) -> SQLCandidate:
        if intent.task_type == "data_quality":
            return self._data_quality_sql(schema)
        if intent.task_type == "trend":
            return self._trend_sql(schema, intent)
        if intent.task_type == "ranking":
            return self._ranking_sql(schema, intent)
        if intent.task_type == "comparison":
            return self._comparison_sql(schema, intent)
        if intent.task_type == "distribution":
            return self._distribution_sql(schema, intent)
        if intent.task_type == "correlation":
            return self._correlation_sql(schema, intent)
        if intent.task_type == "contribution_analysis":
            return self._contribution_sql(schema, intent)
        if intent.task_type == "drill_down":
            return self._comparison_sql(schema, intent)
        if intent.task_type == "outlier_detection":
            return self._distribution_sql(schema, intent)
        if intent.task_type == "lookup":
            return self._lookup_sql(schema)
        return self._aggregation_sql(schema, intent)

    def _contribution_sql(self, schema: TableSchema, intent: IntentResult) -> SQLCandidate:
        metric = self._metric(schema, intent)
        dimension = self._dimension(schema, intent)
        time_col = self._time_column(schema, intent)
        if not metric or not dimension or not time_col:
            return self._cannot_answer("Contribution analysis needs metric, dimension, and time column.")
        month_expr = f"strftime(CAST({quote_identifier(time_col)} AS TIMESTAMP), '%Y-%m')"
        sql = (
            f"SELECT {month_expr} AS month, {quote_identifier(dimension)}, "
            f"SUM({quote_identifier(metric)}) AS total_{metric} "
            f"FROM {quote_identifier(schema.table_name)} "
            f"GROUP BY month, {quote_identifier(dimension)} "
            f"ORDER BY month, {quote_identifier(dimension)} "
            f"LIMIT {self.max_result_rows}"
        )
        return SQLCandidate(
            sql=sql,
            used_tables=[schema.table_name],
            used_columns=[time_col, dimension, metric],
            reasoning="Prepares period-by-dimension totals for contribution decomposition.",
            generated_from_plan=True,
            confidence=0.8,
        )

    def _data_quality_sql(self, schema: TableSchema) -> SQLCandidate:
        table = quote_identifier(schema.table_name)
        selects: list[str] = []
        for column in schema.column_names:
            col = quote_identifier(column)
            selects.append(
                "SELECT "
                f"'{column}' AS column_name, "
                f"SUM(CASE WHEN {col} IS NULL THEN 1 ELSE 0 END) AS missing_count, "
                "COUNT(*) AS row_count "
                f"FROM {table}"
            )
        sql = " UNION ALL ".join(selects)
        return SQLCandidate(
            sql=f"{sql} LIMIT {self.max_result_rows}",
            used_tables=[schema.table_name],
            used_columns=schema.column_names,
            reasoning="Checks null counts for every column.",
        )

    def _trend_sql(self, schema: TableSchema, intent: IntentResult) -> SQLCandidate:
        metric = self._metric(schema, intent)
        time_col = self._time_column(schema, intent)
        if not metric or not time_col:
            return self._cannot_answer("A trend question needs a metric and a time column.")
        dimension = self._dimension(schema, intent, allow_empty=True)
        agg = self._aggregation(intent)
        metric_alias = self._metric_alias(agg, metric)
        month_expr = f"strftime(CAST({quote_identifier(time_col)} AS TIMESTAMP), '%Y-%m')"
        select_parts = [f"{month_expr} AS month"]
        group_parts = ["1"]
        order_parts = ["1"]
        used_columns = [time_col, metric]
        if dimension:
            select_parts.append(quote_identifier(dimension))
            group_parts.append(quote_identifier(dimension))
            order_parts.append(quote_identifier(dimension))
            used_columns.append(dimension)
        select_parts.append(f"{self._agg_expr(agg, metric)} AS {quote_identifier(metric_alias)}")
        sql = (
            f"SELECT {', '.join(select_parts)} "
            f"FROM {quote_identifier(schema.table_name)} "
            f"GROUP BY {', '.join(group_parts)} "
            f"ORDER BY {', '.join(order_parts)} "
            f"LIMIT {self.max_result_rows}"
        )
        return SQLCandidate(
            sql=sql,
            used_tables=[schema.table_name],
            used_columns=used_columns,
            reasoning="Groups the metric by month and optional dimension.",
        )

    def _ranking_sql(self, schema: TableSchema, intent: IntentResult) -> SQLCandidate:
        metric = self._metric(schema, intent)
        dimension = self._dimension(schema, intent)
        if not metric or not dimension:
            return self._cannot_answer("A ranking question needs a metric and a dimension.")
        agg = self._aggregation(intent)
        alias = self._metric_alias(agg, metric)
        direction = str(intent.options.get("sort_direction", "desc")).upper()
        if direction not in {"ASC", "DESC"}:
            direction = "DESC"
        top_n = int(intent.options.get("top_n", 5))
        sql = (
            f"SELECT {quote_identifier(dimension)}, "
            f"{self._agg_expr(agg, metric)} AS {quote_identifier(alias)} "
            f"FROM {quote_identifier(schema.table_name)} "
            f"GROUP BY {quote_identifier(dimension)} "
            f"ORDER BY {quote_identifier(alias)} {direction} "
            f"LIMIT {max(1, min(top_n, self.max_result_rows))}"
        )
        return SQLCandidate(
            sql=sql,
            used_tables=[schema.table_name],
            used_columns=[dimension, metric],
            reasoning="Ranks dimension values by an aggregated metric.",
        )

    def _comparison_sql(self, schema: TableSchema, intent: IntentResult) -> SQLCandidate:
        metric = self._metric(schema, intent)
        dimension = self._dimension(schema, intent)
        if not metric or not dimension:
            return self._cannot_answer("A comparison question needs a metric and a dimension.")
        agg = self._aggregation(intent)
        alias = self._metric_alias(agg, metric)
        sql = (
            f"SELECT {quote_identifier(dimension)}, "
            f"{self._agg_expr(agg, metric)} AS {quote_identifier(alias)} "
            f"FROM {quote_identifier(schema.table_name)} "
            f"GROUP BY {quote_identifier(dimension)} "
            f"ORDER BY {quote_identifier(alias)} DESC "
            f"LIMIT {self.max_result_rows}"
        )
        return SQLCandidate(
            sql=sql,
            used_tables=[schema.table_name],
            used_columns=[dimension, metric],
            reasoning="Compares dimension values with an aggregated metric.",
        )

    def _aggregation_sql(self, schema: TableSchema, intent: IntentResult) -> SQLCandidate:
        metric = self._metric(schema, intent)
        if not metric:
            return self._cannot_answer("No numeric metric was found for aggregation.")
        agg = self._aggregation(intent)
        alias = self._metric_alias(agg, metric)
        sql = (
            f"SELECT {self._agg_expr(agg, metric)} AS {quote_identifier(alias)} "
            f"FROM {quote_identifier(schema.table_name)} "
            f"LIMIT {self.max_result_rows}"
        )
        return SQLCandidate(
            sql=sql,
            used_tables=[schema.table_name],
            used_columns=[metric],
            reasoning="Aggregates the requested metric.",
        )

    def _distribution_sql(self, schema: TableSchema, intent: IntentResult) -> SQLCandidate:
        metric = self._metric(schema, intent)
        if not metric:
            return self._cannot_answer("A distribution question needs a numeric metric.")
        sql = (
            f"SELECT {quote_identifier(metric)} "
            f"FROM {quote_identifier(schema.table_name)} "
            f"WHERE {quote_identifier(metric)} IS NOT NULL "
            f"LIMIT {self.max_result_rows}"
        )
        return SQLCandidate(sql, [schema.table_name], [metric], "Returns values for distribution analysis.")

    def _correlation_sql(self, schema: TableSchema, intent: IntentResult) -> SQLCandidate:
        metrics = intent.metric_candidates[:2]
        if len(metrics) < 2:
            metrics = [c.name for c in schema.columns_by_semantic("metric")[:2]]
        if len(metrics) < 2:
            return self._cannot_answer("A correlation question needs two numeric metrics.")
        col_a, col_b = metrics[0], metrics[1]
        sql = (
            f"SELECT {quote_identifier(col_a)}, {quote_identifier(col_b)} "
            f"FROM {quote_identifier(schema.table_name)} "
            f"WHERE {quote_identifier(col_a)} IS NOT NULL "
            f"AND {quote_identifier(col_b)} IS NOT NULL "
            f"LIMIT {self.max_result_rows}"
        )
        return SQLCandidate(sql, [schema.table_name], [col_a, col_b], "Returns two metrics for correlation analysis.")

    def _lookup_sql(self, schema: TableSchema) -> SQLCandidate:
        sql = f"SELECT * FROM {quote_identifier(schema.table_name)} LIMIT {self.max_result_rows}"
        return SQLCandidate(
            sql=sql,
            used_tables=[schema.table_name],
            used_columns=schema.column_names,
            reasoning="Returns a table preview.",
        )

    def _metric(self, schema: TableSchema, intent: IntentResult) -> str:
        for candidate in intent.metric_candidates:
            if schema.get_column(candidate):
                return candidate
        metrics = schema.columns_by_semantic("metric")
        return metrics[0].name if metrics else ""

    def _dimension(
        self,
        schema: TableSchema,
        intent: IntentResult,
        allow_empty: bool = False,
    ) -> str:
        for candidate in intent.dimension_candidates:
            if schema.get_column(candidate):
                return candidate
        if allow_empty:
            return ""
        categories = schema.columns_by_semantic("category")
        return categories[0].name if categories else ""

    def _time_column(self, schema: TableSchema, intent: IntentResult) -> str:
        for candidate in intent.time_column_candidates:
            if schema.get_column(candidate):
                return candidate
        times = schema.columns_by_semantic("time")
        return times[0].name if times else ""

    def _aggregation(self, intent: IntentResult) -> str:
        agg = str(intent.options.get("aggregation", "sum")).lower()
        return agg if agg in {"sum", "avg", "min", "max", "count"} else "sum"

    def _agg_expr(self, agg: str, metric: str) -> str:
        if agg == "count":
            return "COUNT(*)"
        return f"{agg.upper()}({quote_identifier(metric)})"

    def _metric_alias(self, agg: str, metric: str) -> str:
        if agg == "count":
            return "row_count"
        return f"{agg}_{metric}"

    def _cannot_answer(self, message: str) -> SQLCandidate:
        return SQLCandidate(
            sql="",
            used_tables=[],
            used_columns=[],
            reasoning=message,
            cannot_answer=True,
            error_message=message,
        )
